version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true # yarnコマンドの実行のために追加
    tty: true # yarnコマンドの実行のために追加
    environment:
      RAILS_ENV: development # Railsの環境を指定
      NODE_ENV: development # Node.jsの環境を指定

volumes:
  postgresql-data:
    driver: local
