version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      RAILS_ENV: development
      NODE_ENV: development
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 256m
    ports:
      - 4444:4444
volumes:
  postgresql-data:
    driver: local
