databases:
  - name: pg
    databaseName: (後でRenderで設定するDBのDatabase名）
    user: (後でRenderで設定するDBへのログインID）
    region: (後でRenderで設定するDBのリージョン）

services:
  - type: web
    name: (後でRenderで設定するWEBアプリ名）
    env: ruby
    region: (後でRenderで設定するWEBアプリのリージョン）
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: (後でRenderで設定するWEBアプリ名）
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false