# load 'db/seeds/01_users.rb'
# load 'db/seeds/02_recipes.rb'
# load 'db/seeds/03_RecipeTag.rb'
# load 'db/seeds/04_RecipeTypeOfTags.rb'
# load 'db/seeds/05_Ingredient.rb'
load 'db/seeds/06_favorite.rb'
# load 'db/seeds/07_wisdom_board.rb'
load 'db/seeds/08_favorite_wisdom.rb'
# load 'db/seeds/09_wisdom_tag.rb'
# load 'db/seeds/10_wisdom_tag_type_og_tag.rb'
load 'db/seeds/11_favorite_wisdom.rb'
